language: node_js
node_js:
  - "stable"
language: python 
python: 
- "3.9"
before_script:
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
install:
 - pip install -r requirements.txt
 - pip install codacy-coverage
 - pip install selenium
script:
  - cd bar-trender-front-end
  - npm install
  - cd src/tests
  - pytest test_all.py
